config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get   'signup', to:'users#new'
  get   'login',  to:'sessions#new'
  post  'login',  to:'sessions#create'
  delete'logout', to:'sessions#destroy'
  
  resources :users
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get 'followings' , 'followers'
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user #れぞれの投稿は特定の1人のユーザーのものである
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password                                                     #パスワードのセキュリティー
  has_many :microposts                                                    #それぞれのユーザーは複数の投稿を持つことができる。
  has_many :following_relationships, class_name:  "Relationship",         #関連を設定するモデルクラス名を指定。
                                     foreign_key: "follower_id",          #フォローしている人のIDがキーに
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
                                                                       #through(スルー)経由するsource元となるオブジェクトを指定
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end

end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def logged_in_user
    unless logged_in?          #「unless」false場合(ログインしていない)の処理する
      store_location           #アクセスしているurlを保存
      flash[:dander] = "Please log in."
      redirect_to login_url    #ログイン画面のURLにリダイレク
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]  #ログインしていないuserはloginページへ(ApplicationController)
    
    def create
      @micropost = current_user.microposts.build(micropost_params) #build = newに似ているが親要素への結びつき外部参照キーを自動でセット
      if @micropost.save                                           #パラメータを受け取って現在のユーザーに紐付いたMicropostのインスタンスを作成          
        flash[:success] = "Micropost created!"
        redirect_to root_url
      else
        render 'static_pages/home'
      end
    end
    
    def destroy
      @micropost = current_user.microposts.find_by(id: params[:id])
      return redirect_to root_url if @micropost.nil?
      @micropost.destroy                                             #destroy=データベースから削除
      flash[:success] = "Micropos deleted"
      redirect_to request.referrer || root_url                      #referrer=該当ページに遷移する直前に閲覧されていた参照元url
    end                                                             #||　または　or　　　　
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
   before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    #binding.pry
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
  end
end

#ログインしている場合は、新しいMicropostクラスのインスタンスをuser_idを紐付けた状態で初期化します。
#current_user.microposts.buildは、Micropost.new(user_id: current_user.id)と同じです。
#前者の方はcurrent_userのhas_many :micropostsで生成されるbuildメソッドを使用していて、
#確実にuser_idが紐付いたデータを作成できるのでこちらを使用するようにしましょう。

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc) #oder取得した値を並び替え desc降順
  end
  
  def edit 
  end
  
  def update 
    if @user.update(user_params)
      flash[:success] = "編集しました"
      redirect_to user_path 
      else
        render 'edit'
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "welcome to the Sample App!"
      redirect_to @user 
    else
      render'new'
    end
  end
  
  def followings
    @user  = User.find(params[:id])
    @users = @user.following_users
  end
  
  def followers
    @user  = User.find(params[:id])
    @users = @user.follower_users
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :profile)
  end
  

  
  def set_user
    @user = User.find(params[:id])
  end
  
  def check_user
    if @user != current_user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
   #||=は左の値がfalseかnilの場合にsession[:user_id]の値に一致するユーザーを左に代入
   
  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end
  #リクエストがもしGETの場合リクエストのURLをforwardingに保存しておく

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#patern03">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Microposts", root_path, id: "logo" %>
      </div>
      <div id="patern03" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
         </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message|%>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                        data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<span class="gravatar_saide"><%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_asidebar.html.erb
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %><br>
      </h1>
      <p><span class="label label-info">年齢</span> <%= @user.age %>才</p>
      <p><span class="label label-info">プロフィール</span> <%= @user.profile %></p>
      <p><%= link_to 'Followings', followings_user_path(@user) %></p>
      <p><%= link_to 'Followers', followers_user_path(@user) %></p>
    </section>
  </aside>
  

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Plofile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for @user do |f| %>
          
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
    
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
          
          <%= f.label :age %>
          <%= f.number_field :age, class: 'form-control' %>
    
          <%= f.label :profile %>
          <%= f.text_area :profile, class: 'form-control' %>
    
          <%= f.label :password %>
          <%= f.password_field :password , class: 'form-control'%>
    
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation , class: 'form-control'%>
    
          <%= f.submit "Up date", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <%= render 'asidebar' %>
  <div class="col-md-8">
    <h3 class="text-center">フォロワー一覧</h3>
    <div class="container-fluid">
       <div class="row">
          <% @users.each.with_index(1) do |user , i| %>
            <% offset = i % 3 != 1 ? "col-xs-offset-1" : nil %>
            <div class="col-xs-3 <%= offset %>">
              <p class="text-center">
                <%= gravatar_for @user, user %><br>
                <%= link_to user.name, user %>
              </p>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <%= render 'asidebar' %>
  <div class="col-md-8">
    <h3 class="text-center">フォロー一覧</h3>
    <div class="container-fluid">
       <div class="row">
          <% @users.each.with_index(1) do |user , i| %>
            <% offset = i % 3 != 1 ? "col-xs-offset-1" : nil %>
            <div class="col-xs-3 <%= offset %>">
              <p class="text-center">
                <%= gravatar_for @user, user %><br>
                <%= link_to user.name, user %>
              </p>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <%= render 'asidebar' %>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>                               <!-- any=モデルが空ならtrueを返す-->
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>                                <!--/_micropost.html.erbを順番に渡してる？-->
      </ol>
    <% end %>
  </div>
</div>